---
title: "Bahrain COVID Stats"
output:
  distill::distill_article:
    self_contained: false
---

```{r ,include=FALSE}
library(tidyverse)
library(here)
library(ggplot2)
library(sparkline)
library(DT)
library(kableExtra)
library(gghighlight)
library(plotly)
library (patchwork) 
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
options(scipen = 1e6)
```
```{css ,echo = FALSE}

h1{
  color: red;
  font-size: 50px;
}

h2{
  color: grey;
  font-size: 20px;
}

thead {
  background-color: #006DAE;
  color: white;
}


```

```{r read,include=FALSE}
covid <- read_csv(here::here("data/bahrain-covid-data.csv"))
```
```{r read1,include=FALSE}
covid_bahrain <- covid %>% 
 filter(location == "Bahrain")
```

```{r read2,include=FALSE}
covid_bahrain_1 <- covid_bahrain %>% 
  select(location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,new_tests,total_tests,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,population,population_density,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,life_expectancy,excess_mortality)

covid_asia <- covid %>% 
  filter(continent == "Asia") %>% 
    select(location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,new_tests,total_tests,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,population,population_density,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,life_expectancy,excess_mortality)



```



The main dataset is of dimensions **`r dim(covid)`**, whereas that of **India** alone is **`r dim(covid_bahrain)`**.

# Analysis & Findings

## What are the top 5 days with maximum covid cases reported

```{r Q1A,echo=FALSE}


covid_bahrain_1 %>% 
  select(date,total_cases,new_cases,new_tests,total_tests) %>% 
  rename("Date" = date,
         "Total_Cases" = total_cases,
         "New_Cases" = new_cases,
         "New_Tests" = new_tests,
         "Total_Tests" = total_tests) %>% 
   slice_max(New_Cases,n = 5) %>% 
  mutate(Perc_New_Cases = round((New_Cases/New_Tests)*100,2)) %>% 
  kable(caption = "Top 5 days with max no of covid cases in Bahrain") %>% 
  kable_styling(bootstrap_options = c("basic","striped,hover"))
```


```{r Q1B,echo=FALSE}
covid_bahrain_1 %>% 
  select(date,total_cases,new_cases,new_tests,total_tests) %>% 
  rename("Date" = date,
         "Total_Cases" = total_cases,
         "New_Cases" = new_cases,
         "New_Tests" = new_tests,
         "Total_Tests" = total_tests) %>% 
  mutate(Perc_New_Cases = round((New_Cases/New_Tests)*100,2)) %>% 
  slice_max(Perc_New_Cases,n = 5) %>% 
  kable(caption = "Top 5 days with max percetage of new covid cases in Bahrain") %>% 
  kable_styling(bootstrap_options = c("basic","striped,hover"))
```

## What are top 5 days with maximum covid vaccinations done ?

```{r}
covid_bahrain_1 %>% 
  select(date,total_vaccinations,new_cases,new_vaccinations) %>% 
  slice_max(new_vaccinations,n = 5) %>% 
  kable(caption = "Top 5 days with max covid vaccinations done") %>% 
  kable_styling(bootstrap_options = c("basic","striped,hover"))
```

## What are top 5 days with maximum deaths due to covid ?

```{r}
covid_bahrain_1 %>% 
  select(date,total_deaths,new_cases,new_deaths) %>% 
  slice_max(new_deaths,n = 5) %>% 
  kable(caption = "Ttop 5 days with maximum deaths due to covid") %>% 
  kable_styling(bootstrap_options = c("basic","striped,hover"))
```
# Data Story 1 (Wihthin Continent)

```{r}
covid_asia_loc <- covid_asia %>% 
  filter(date == "2021-09-12") %>% 
  slice_max(total_cases,n=5) %>% 
  select(location)

covid_asia_loc1 <- covid_asia_loc$location

graph1 <- covid_asia %>% 
  filter(location == "Bahrain" | location %in% covid_asia_loc1) %>% 
  separate(date, into = c("Year","Month","Day")) %>% 
  group_by(location,Year,Month) %>% 
  summarise(Mon_new_cases = sum(new_cases)) %>% 
  mutate(Year = as.factor(Year),
         Month = as.numeric(Month)) %>% 
  ggplot(aes(Month,
             Mon_new_cases,
             color = location)) +
  geom_line() +
  scale_x_continuous(breaks = seq(1,12,1)) +
  geom_point() +
  ylab("Total Monthly Cases") +
  ggtitle("Trend of monthly Covid Cases per year") +
  theme_bw() +
#   gghighlight(location == "Bahrain" | location %in% covid_asia_loc1) +
  facet_wrap(~Year) 
ggplotly(graph1)





```










```


